typedb/bazel-distribution

npm/rules.bzl, npm/templates/BUILD, npm/templates/deploy.sh
Rule adds `deploy_npm` Bazel rule.
Facilitate deployment of `npm_package` targets to NPM
```
deploy_npm(
name = "deploy-npm",
target = ":target-to-deploy,
version_file = "//:VERSION",
deployment_properties = "//:deployment.properties",
)
```
`bazel run //:deploy-npm -- <npm-username> <npm-password> <npm-email>`
`package.json` should contain a placeholder version of `0.0.0-development` which will be replaced with a string from `version_file`
`deployment_properties` should contain `npm.repository_url=REPO_URL` where `REPO_URL` is a valid NPM repo URL
Handles these tasks:
* logs in to NPM with credentials read from command line arguments
* updates version statement in `package.json`
* runs `npm publish` to push an updated archive to NPM
=> Rule for deploying NPM packages

distribution/BUILD, distribution/archiver.py, distribution/rules.bzl
Adds a rule which allows you to pack `java_binary` targets together with their dependencies, additional files and empty directories. Produces a `.zip` as a result
Sample usage:
```
distribution(
name = "distribution",
targets = ["//server:server-binary"],
additional_files = {
"//:grakn": 'grakn',
"//server:conf/logback.xml": "conf/logback.xml",
"//server:conf/grakn.properties": "conf/grakn.properties",
"//server:services/cassandra/cassandra.yaml": "services/cassandra/cassandra.yaml",
"//server:services/cassandra/logback.xml": "services/cassandra/logback.xml",
"//server:services/grakn/grakn-core-ascii.txt": "services/grakn/grakn-core-ascii.txt"
},
empty_directories = [
"db/cassandra",
"db/queue"
],
visibility = ["//visibility:public"]
)
```
=> Implement rules for building zip distribution

github/dependencies.bzl
Native [`http_file`](https://docs.bazel.build/versions/master/be/workspace.html#http_file) is now deprecated
=> Fix removed native bazel rules (http_file)

distribution/rules.bzl, maven/templates/rules.bzl
Fixes future-incompatible change: `depset` will be [no longer iterable](https://docs.bazel.build/versions/master/skylark/backward-compatibility.html#depset-is-no-longer-iterable) in future version of `bazel`
=> Fix 'depset_is_not_iterable' incompatible change

distribution/java_deps.py, distribution/rules.bzl
This PR adds the following:
* `java_deps` rule which takes in `java_binary` and puts it together will all dependencies into a `.tgz` archive at directory `java_deps_root`. This is only meant for internal consumption of `pkg_deb`
* `deploy_deb` macro which builds final `.deb`:
```
deploy_deb(
name = "X"
)
```
Resulting Debian package will be called `X`, target to build it is `//:X-deb`
=> Rules for Debian distribution

distribution/BUILD, distribution/rules.bzl, distribution/tgz2zip.py
* Renames `distribution` (rule) and `_distribution_impl` (rule implementation) to `old_distribution` and `old_distribution_impl`. Those are subject to removal.
* Adds `tgz2zip` rule, which converts `tar` archives to `zip` (used in new `distribution` macro)
* `java_deps` now only takes single target and does _not_ generate `.py` file to execute which caused collisions
* Reimplement `distribution` as a macro, which expands into sequence `java_deps` -> `pkg_tar` -> `tgz2zip`
* Rename `deploy_deb` to `linux_distributions` — macro, which expands into sequence `java_deps` -> `pkg_tar` -> {`pkg_deb`, `pkg_rpm`}
=> Impl. Linux packaging rules, reimpl. distribution rule

distribution/rules.bzl, distribution/tgz2zip.py
Modifies `distribution` in such a way that it produces an archive, in which contents are prepended by extra directory, i.e. for `//:distribution` of [graknlabs/grakn](https://github.com/graknlabs/grakn/), when unpacking, it would produce folder structure resembling this:
```
./grakn-core-all/
./grakn-core-all/conf/
./grakn-core-all/console/…
./grakn-core-all/grakn
./grakn-core-all/logs/
./grakn-core-all/server/…
```
This restores the behaviour we previously had.
=> Put distribution into its own folder _inside_ the archive

distribution/rules.bzl
```
distribution(
name = "kekeke", # can specify name
targets = {
"//runner:benchmark-runner": "runner/services/lib/",
},
additional_files = {
"//runner:runner": 'runner.sh'
},
empty_directories = [
"data/logs"
],
output_filename = "benchmark-runner",
)
```
=> the distribution() macro now takes in 'name' attribute

distribution/rules.bzl
As stated in the title, renames `deploy_*` rules to `distribution_*`. After this, we'll create `deploy_*` rules which perform the actual deployment.
=> Rename deploy_(deb|rpm) to distribution_(deb|rpm); fix #17

distribution/rules.bzl, distribution/tgz2zip.py
* Adds `distribution_structure`, `distribution_zip`, `distribution_deb`, `distribution_rpm` macros — see issue description for details
* Removes `distribution` macro
=> Restructure distribution rules; fix #20

deb/deployment/rules.bzl, deb/templates/BUILD, deb/templates/deploy.sh
Adds `deploy_deb` rule.
Sample usage:
```
load("@graknlabs_rules_deployment//deb/deployment:rules.bzl", "deploy_deb")
…
deploy_deb(
name = "deploy-deb",
target = ":distribution-deb",
deployment_properties = "//:deployment.properties",
)
```
=> Rules for deploying DEB packages (fix #24)

pip/templates/deploy.sh
The `deploy_pip()` rule expects a certain set of libraries to be installed system-wide or it will fail to execute otherwise. You can't provide them via a `BUILD` file.
This isn't ideal as the Bazel approach is that you're supposed to declare transitive dependencies in the `BUILD` file.
Specifically, the aforementioned "set of libraries" are libraries needed by `twine`, which is used internally by `deploy_pip()`.
I had those dependencies installed system-wide on my machine, which is why the problem only manifests when James tried to run the command on the CI machine and on his computer.
Made `deploy_pip()` able to read that set of libraries from the `BUILD` file so they don't have to be installed system-wide on that machine.
—
N/A
=> deploy_pip is now able to use dependencies provided via requirements specified in the BUILD file (fix #26)

pip/BUILD, pip/requirements.txt, pip/rules.bzl, pip/templates/deploy.sh
Adds `deps` to `deploy_pip` rule which expects you to pass all deps that are required for deployment to `pip`
=> add `deps` attribute to deploy_pip

npm/templates/deploy.sh
For targets at root package, `$BAZEL_PACKAGE_NAME` is empty and therefore directory to `cd` in expands into incorrect one
Before:
`//client-nodejs:deploy-npm` → `client-nodejs/deploy-npm`
`//:deploy-npm` → `/deploy-npm`
After:
`//client-nodejs:deploy-npm` → `./client-nodejs/deploy-npm`
`//:deploy-npm` → `.//deploy-npm`
=> Fix npm deployment for targets at root package (i.e. //:target)

pip/rules.bzl, pip/templates/deploy.sh
* `cd`-ing into directory breaks [graknlabs/kglib](https://github.com/graknlabs/kglib) deployment
* not `cd`-ing into directory _does not_ break [graknlabs/client_python](https://github.com/graknlabs/client_python), because `$PKG_DIR` is `''` for `//:client_python` anyway
=> Fix pip deployment

pip/rules.bzl
When `py_replace_imports` is used indirectly, it needs to replace workspace name which is duplicated twice in `file.short_path`
This fixes this error:
```
Output artifact 'external/graknlabs_client_python/graknlabs_client_python/rpc/protocol/session/Session_pb2.py' not under package directory 'external/graknlabs_client_python/grakn' for target '@graknlabs_client_python//grakn:rpc'
```
=> BUGFIX: replace duplicate workspace name if rule is user from other repo

distribution/BUILD, distribution/java_deps.py, distribution/rules.bzl
* `java_deps` and `tgz2zip` are now real Bazel targets instead of exported Python scripts
* pass jar file mapping in a file instead of cmdline argument to avoid hitting limits on Windows
=> Bugfixes for building distribution on Windows

npm/templates/deploy.sh
Based on https://unix.stackexchange.com/a/92907
=> Use cross-platform options for 'sed'; fixes deploy_npm rule on Linux

npm/templates/deploy.sh
1. `SNAPSHOT` in version is replaced with actual commit SHA1 of the repo
2. `package.json.bak` is now removed forcibly to avoid extra question which may stop the deployment
Example output filename: `grakn-1.5.0-594687d9b9752312081d3a37c72bd5d27f38d50e.tgz`
=> Fix version for deploy_npm

pip/templates/deploy.sh
Similarly to #55:
`SNAPSHOT` in version is replaced with actual commit SHA1 of the repo
=> Fix version for deploy_pip

apt/templates/deploy.sh, maven/templates/deploy.sh, npm/templates/deploy.sh, pip/templates/deploy.sh, rpm/templates/deploy.sh
1. make method name clearer that it contains credentials, for the eyes of developers
2. prevent grabl credential from being exposed in print statements
=> prevent deployment credential from being exposed

rpm/rules.bzl
Fixes #47
Rewrites `assemble_rpm` macro in such a way that it produces a meaningful output file
Examples:
`//server:assemble-rpm` -> `bazel-genfiles/server/grakn-core-server.rpm`
`//console:assemble-rpm` -> `bazel-genfiles/console/grakn-core-console.rpm`
`//bin:assemble-rpm` -> `bazel-genfiles/bin/grakn-core-bin.rpm`
=> Rename RPM output name so it's clear which target is built

common/rules.bzl
Fixes #67
Rewrites `assemble_targz` macro in such a way that it produces a meaningful output file
Examples:
`//:assemble-linux-targz` -> `bazel-genfiles/grakn-core-all-linux.tar.gz`
`//server:assemble-linux-targz` -> `bazel-genfiles/server/grakn-core-server.tar.gz`
`//console:assemble-linux-targz` -> `bazel-genfiles/console/grakn-core-console.tar.gz`
`//bin:assemble-bash-targz` -> `bazel-genfiles/bin/assemble-bash-targz.tar.gz`
=> Use output_filename while choosing name for assemble_targz output

rpm/rules.bzl
Fix `deploy_rpm` bug (closes #70)
Previously `deploy_rpm` was expecting to get `pkg_rpm` target, specifically, for `_collect_rpm_package_name` aspect to read `spec_file`. Since `deploy_rpm` now takes the output of `assemble_rpm`, which is a `genrule`, we add a proper tag to output target of `assemble_rpm` and configure aspect to read from that tag instead
=> Fix broken deploy_rpm rule

common/java_deps.py, common/rules.bzl
Properly name JARs inside distributions
* `_collect_maven_coordinate` aspect which associates `{file_name: maven_coordinate}` pair to each Java target
* `_transitive_collect_maven_coordinate` aspect which collects all of pairs associated by previous aspect and associated them to _one_ target we have access to in `java_deps` rule implementation
* `java_deps` now requires you give it `version_file` so it knows how to version artifacts with `{pom_version}` string
=> Fix naming for Maven JARs inside distributions

github/deploy.py, github/rules.bzl
Support GitHub deployment for multiple targets at once. Also, support optional release description.
- New rule attribute: `targets`
- New rule attribute: `release_description`
- Symlink `deployment.properties` at execution root to actual file so it doesn't have to be hardcoded
=> Support for multiple targets in deploy_github

apt/templates/deploy.sh, npm/templates/deploy.sh, pip/templates/deploy.sh, rpm/templates/deploy.sh
`deploy_(apt|rpm|npm|pip)` rules now accept credentials via environment variables: `$DEPLOYMENT_REPO_TYPE`, `$DEPLOYMENT_USERNAME`, `$DEPLOYMENT_PASSWORD`, `$DEPLOYMENT_EMAIL` [for `npm`]
This is done so we're able to not expose our credentials (`bazel` prints out command being executed and the behaviour is non-configurable)
- Remove `$#` check for number of arguments
- If command line argument was not passed, default to environment variable (see above); if it's also not present, default to `notset`, see [this guide](https://unix.stackexchange.com/a/62337)
- Check that credential is not set to "notset`; exit with error if it is
=> Accept credentials from environment variable in deployment rules

github/rules.bzl
`deploy_github` should not enforce taking single `target` as argument
- Removed `mandatory=True` on `deploy_github` rule definition
=> Make 'target' attribute non-mandatory for deploy_github

github/rules.bzl
Fix `deploy_github` rule so it works when you don't specify single target
Add a condition to not add `ctx.file.target` it it's not set
=> Bugfix deploy_github rule

maven/BUILD, maven/_pom_replace_version.py, maven/templates/deploy.py, maven/templates/rules.bzl
`assemble_maven` can now use information about dependencies that is declared using `git_repository` for when generating `pom.xml`
=> assemble_maven uses the commit id of git_repository dependencies when writing pom.xml

maven/_pom_replace_version.py, maven/templates/deploy.py
Update `deploy_maven()` to accept a version string is different depending on whether you are deploying to the `snapshot` or `release` repository:
1. deployment to `snapshot`: must be a valid a git commit id
2. deployment to `release`: must be a valid version string that follows the `x.y.z` format (eg., `1.5.0`)
Example:
```
bazel run //:deploy-maven -- snapshot $(git rev-parse HEAD) $USER $PASS
bazel run //:deploy-maven -- release $(cat VERSION) $USER $PASS
```
1. The `assemble_maven` rule produces a Maven artifact which is not versioned
2. The `deploy_maven()` rule is updated to accept version. More specifically, the change is done in `deploy.py`
=> deploy_maven() accepts 'version' in the command line argument

github/deploy.py
[graknlabs/client-python](https://github.com/graknlabs/client-python), [graknlabs/client-nodejs](https://github.com/graknlabs/client-nodejs), [graknlabs/graql](https://github.com/graknlabs/graql) all require GitHub releases with no files (actual artifacts are deployed to PyPI, NPM and Maven, respectively)
- Add a filtering statement so that we have `[]` (empty list) instead of `['']` (a list with an empty string)
- Create a dummy directory inside directory without artifacts to allow `ghr` to proceed uploading
=> Allow deploy_github rule to deploy releases with no files

maven/templates/deploy.py, maven/templates/rules.bzl
If you supply a custom `deployment_properties`, the command will fail:
```
deploy_maven(
name = "deploy-maven",
target = ":assemble-maven",
deployment_properties = "//a/custom:deployment.properties"
)
bazel run //java:deploy-maven -- release (cat VERSION) $user $pass
...
File "/private/var/tmp/_bazel_lolski/f1893223ba4c11af3d06827cbf1a1b3f/execroot/graknlabs_graql/bazel-out/darwin-fastbuild/bin/java/deploy.py", line 71, in <module>
deployment_properties = parse_deployment_properties('external/graknlabs_build_tools/deployment.properties')
File "/private/var/tmp/_bazel_lolski/f1893223ba4c11af3d06827cbf1a1b3f/execroot/graknlabs_graql/bazel-out/darwin-fastbuild/bin/java/deploy.py", line 19, in parse_deployment_properties
with open(fn) as …
```
=> deploy-maven: fix an issue with supplying custom deployment.properties

github/deploy.py
`deploy_github` should be able to get credential from environment without needing to expose it in command line arguments
Separate logic of obtaining token into a separate function
=> Allow getting GitHub credential from enviroment variable

brew/rules.bzl, brew/templates/deploy.py
Workbase, being a graphical app, requires a _cask_ instead of a brew formula. Thankfully, we can use the same tap ([graknlabs/homebrew-tap](https://github.com/graknlabs/homebrew-tap)), but folder layout is a little bit different.
Modify folder in which formula is created (`Formula`/`Casks` based on formula type)
=> Support Caskroom deployments for deploy_brew

brew/rules.bzl, brew/templates/deploy.py
Workbase builds are done outside of `bazel`, which would not allow us to pass `checksum` to `bazel` target
- Make `checksum` attribute non-mandatory in `deploy_brew`
- Refactor getting checksum logic into a separate function which either reads a file, reads an env variable or throws an error.
=> Allow getting sha256 checksum from env variable instead of bazel target

apt/templates/deploy.sh, rpm/templates/deploy.sh
Currently, `deploy_apt` and `deploy_rpm` rules only accepts `test` repository.
This PR updates them so they accept `release` repository in addition to `test`:
```
DEPLOYMENT_REPO_TYPE=release DEPLOYMENT_USERNAME=... DEPLOYMENT_PASSWORD=... bazel run //bin:deploy-apt
```
=> apt and rpm rules should accept release repository

github/deploy.py
Add version to the filename of distributions that are uploaded to GitHub:
- grakn-core-server-windows-1.5.0.zip
- grakn-core-console-mac-1.5.0.zip
- grakn-core-server-1.5.0.tar.gz
- grakn-core-console-1.5.0.tar.gz
- grakn-core-all-mac-1.5.0.zip
- grakn-core-all-windows-1.5.0.zip
- grakn-core-console-windows-1.5.0.zip
- grakn-core-all-linux-1.5.0.tar.gz
- grakn-core-server-mac-1.5.0.zip
=> deploy_github - uploaded distribution should contain version numbers

apt/pkg_deb_modified_from_bazel/BUILD, apt/pkg_deb_modified_from_bazel/archive.py, apt/pkg_deb_modified_from_bazel/make_deb.py, apt/pkg_deb_modified_from_bazel/path.bzl, apt/pkg_deb_modified_from_bazel/pkg.bzl, apt/rules.bzl, rpm/rules.bzl
`assemble_apt` should be able to embed version of package being built into its dependency — this way we can make `grakn-core-all=1.5.0` depend exactly on `grakn-core-console=1.5.0` and `grakn-core-server=1.5.0`
- Vendored in `pkg_deb` from `bazel`
- Modified it to replace `{version}` with package version
- Make `installation_dir` non-mandatory so we're able to build empty packages (without files)
=> Assemble apt modifications

apt/templates/deploy.sh, github/deploy.py, maven/templates/deploy.py, npm/templates/deploy.sh, pip/templates/deploy.sh, rpm/templates/deploy.sh
Make error messages on missing env variables helpful
- Fixed variable names in error messages
- Remove ability to pass token via cmdline argument in `deploy_github`
=> Update error messages on non-existent variables

common/rules.bzl
Fixes #93 
`jars.mapping` is now prefix by `target`'s label name, which is unique across targets in same package.
=> Allow multiple java_deps in same file by renaming jars.mapping

github/deploy.py
Fixes #86
Exit with same code as `ghr` exited in `deploy_github` implementation
=> Propogate the exit code of ghr to deploy_github

brew/rules.bzl, brew/templates/deploy.py, common/BUILD, common/assemble-versioned.py, common/rules.bzl, github/deploy.py, github/rules.bzl
Files that are deployed to Github used to look like this: `grakn-core-all-linux.tar.gz` and when extracted will be located in a directory `grakn-core-all-linux`.
With this PR they will look like this: `grakn-core-all-linux-1.5.0.tar.gz` and when extracted will be located in a directory `grakn-core-all-linux-1.5.0`.
A new rule `assemble_versioned` is created. It outputs a distribution which contains the version number. Additionally, `checksum`, and `deploy_github` takes input from `assemble_versioned` rather than `assemble_zip` and `assemble_tar`
=> Distribution versioning and checksum

pip/templates/deploy.sh
Previously, `deploy_pip` would've generated `-py2.whl` files. We want to have 'universal' wheel files available for both python2 and python3
Added `setup.cfg` to configure `wheel`. from [doc ref](https://wheel.readthedocs.io/en/stable/user_guide.html#building-wheels):
>If your project contains no C extensions and is expected to work on both Python 2 and 3, you will want to tell wheel to produce universal wheels by adding this to your setup.cfg file: …
=> Make deployed .whl files universal (py2/py3)

github/deploy.py
Closes https://github.com/graknlabs/bazel-distribution/issues/107
`deploy_github` creates a Github draft which points to the latest `master` instead of the commit id from which the release is made from.
This behavior is incorrect and in this PR, we changed the behavior where `deploy-github` must be supplied with "target commit id":
```
bazel run //:deploy-github -- <target-commit-id>
```
Accepts "target commit id" as an argument and supply it to `ghr` so that it creates a draft that correctly points to the right commit id instead of latest `master`
=> deploy_github - the release should set the commit id properly

maven/_pom_replace_version.py
Fixes #113
JARs built by `assemble_maven` are now versioned properly
=> Replace {pom_version} with actual version

packer/dependencies.bzl, packer/rules.bzl, packer/templates/BUILD, packer/templates/deploy_packer.py
Have `assemble_packer` and `deploy_packer` rules useful in deployment to cloud providers, such as AWS and GCP.
The rule is essentially a Bazelised version of Hashicorp's [Packer](packer.io).
Implemented `assemble_packer` macro (based on `pkg_tar` provided by `bazel`) and `deploy_packer` rule
Sample usage:
```
assemble_packer(
name = "assemble-gcp",
config = ":gcp.json",
files = {
"//:assemble-linux-targz": "grakn-core-all-linux.tar.gz",
…
}
)
deploy_packer(
name = "deploy-gcp",
target = ":assemble-gcp",
)
```
=> Implement *_packer rules

packer/rules.bzl
Make it possible to have multiple deploy_packer targets in same BUILD file. Right now, if we have multiple `deploy_packer` targets Bazel will fail to build with the following error:
```
ERROR: file 'deploy_packer.py.runfiles.SOURCES' is generated by these conflicting actions:
Label: //:deploy-aws, //:deploy-gcp
```
Use unique name for `ctx.actions.declare_file` based on target's label name
=> Make it possible to have multiple deploy_packer targets in same BUILD file

WORKSPACE, github/dependencies.bzl, github/deploy.py, github/rules.bzl
Simplify `deploy_github`
Utilize `bazel`'s `http_archive` to unpack `ghr` instead of doing it in Python
=> deploy_github rule should use bazel for unpacking

maven/_pom_replace_version.py, maven/templates/deploy.py
There are two `pom.xml`s that got produced, the actual `pom.xml` file and an additional copy which is embedded inside the JAR which servers as metadata.
During the assembly step, these two files should just contain a version placeholder `{pom_version}` rather than the actual version number. The actual version number would only be added during the deployment step.
=> assemble_maven and deploy_maven should produce and upload Maven artifact with the correct pom files

rpm/rules.bzl
Fix #126
Specifying default condition allows build to succeed on Windows.
=> Specify default condition so build works on Windows too

common/generate_json_config.bzl, gcp/BUILD, gcp/packer.template.json, gcp/rules.bzl
First part of making AWS/GCP rules more user-friendly (issue #124)
- Adds `generate_json_config` rule which allows to substitute values in template
- Adds `assemble_gcp` which generates config and calls `assemble_packer`. Sample usage:
```
assemble_gcp(
name = "assemble-gcp-snapshot",
files = GCP_FILES,
install = "//deployment/deploy-gcp-image/files:install.sh",
project_id = "grakn-dev",
zone = "europe-west1-b",
image_name = "grakn-kgms-snapshot-{{user `version`}}",
image_licenses = 'projects/grakn-public/global/licenses/grakn-kgms-premium'
)
```
=> Add assemble_gcp rule that encapsulates generating config

aws/BUILD, aws/packer.template.json, aws/rules.bzl
Second part of making AWS/GCP rules more user-friendly (issue #124)
- Adds `assemble_aws` which generates config and calls `assemble_packer`. Sample usage:
```
assemble_aws(
name = "assemble-aws-snapshot",
ami_name = "grakn-kgms-snapshot-{{user `version`}}",
install = "//deployment/deploy-aws-image/files:install.py",
region = "us-east-1",
files = AWS_FILES
)
```
=> Add assemble_aws rule that encapsulates generating config

common/BUILD, common/assemble-versioned.py, common/common.py
Achieve higher reusability by separating out commonly-used functions.
Separate `ZipFile`, `zip_repackage_with_version` and `tar_repackage_with_version`  into `common/common.py`
=> Separate repackaging functions to common file

BUILD, README.md, WORKSPACE, apt/BUILD, apt/pkg_deb_modified_from_bazel/BUILD, aws/BUILD, brew/BUILD, common/BUILD, doc_hub.bzl, gcp/BUILD, github/BUILD, maven/templates/BUILD, npm/BUILD, packer/BUILD, pip/BUILD, rpm/BUILD
Fix #33
This pull request introduces `README.md` which documents how to use rules in this repo (documentation is gathered from rule implementations and is subject to improve) and surrounding infrastructure which allows building it.
- Use modified version of [`bazelbuild/skydoc`](https://github.com/graknlabs/skydoc) to allow building documentation
- Introduce `bzl_library` targets which expose rule implementations (`.bzl` files)
- Introduce `//:docs` target which builds the documentation (`README.md`). Sample usage:
```
bazel build //:docs
cp bazel-bin/README.md README.md
```
=> Build rules documentation

README.md, maven/templates/deploy.py, maven/templates/pom.xml, maven/templates/rules.bzl
Fix #104
This pull requests allows `assemble_maven` and `deploy_maven` to produce Maven deployments that are compliant with OSSRH guidelines, which allows to proceed with deployment to Maven Central.
- `assemble_maven` now accepts additional values to put in POM: `license`, `project_description`, `project_name`, `project_url`, `scm_url`
- upload sources JAR and JavaDoc JAR
- sign and upload detached signatures (`.asc`) for artifacts
=> Fix Maven rules to produce deployment compliant with Maven Central

README.md, common/java_deps.bzl
Fix #111
In order to help with duplicate names issue, a naming scheme based on Maven coordinates is going to be adopted. To help with its adoption, an attribute that *forces* all artifacts to have Maven coordinates is introduced.
- Add `maven_name` attribute to `java_deps` rule. By default it's `False`, not changing workflow of existing users.
- If `maven_name` attribute is set to True, `fail(…)`  and aspect did not attach maven coordinate to target, fail loudly
=> Option to force Maven naming scheme for java_deps

maven/templates/deploy.py
Fix #137
Previously, Maven repo URLs in `deployment.properties` were expected to have trailing slash. This PR removes such a need and supports both having and not having trailing slashes.
- Use `posixpath.join` as a proper way of concatenating URLs
- Remove unused import of `operator`
=> Maven deployment script should properly concatenate URLs

README.md, github/dependencies.bzl, github/deploy.py, github/rules.bzl
Fix #103
This PR allows supplying custom `title` (optionally appending version) to `deploy_github` targets which allows to further automate release creation.
- Bump `ghr` to `0.12.1` to support `-n` argument (release title)
- Add optional `title` and `title_append_version` arguments to `deploy_github` rule
=> Support custom title in deploy_github rule

brew/rules.bzl, brew/templates/deploy.py, common/BUILD, common/common.py, github/deploy.py, github/rules.bzl, maven/BUILD, maven/deployment_rules_builder.py, maven/templates/deploy.py, maven/templates/rules.bzl
Fix #78 
Previously, every rule implementation `parse_deployment_properties` defined itself which resulted in error-prone duplicated code. This PR moved `parse_deployment_properties` into `//common:common.py` and reuses it across rule implementations.
- Added definition of `parse_deployment_properties` to `common.py`
- Remove multiple definitions of `parse_deployment_properties` across rule implementation Python templates
- Add `common.py` to sandbox when executing rules that need `parse_deployment_properties`
- `//common:deployment_rules_builder` is now a proper Python target. However, `exports_files` is still keeped for transition period until `build-tools` is not updated.
[ref](https://docs.python.org/3/library/runpy.html#runpy.run_path) describes the technique used to import …
=> Only define parse_deployment_properties once

maven/templates/rules.bzl
Typo in `rules.bzl` resulted in incorrectly deploying JAR with `.class` files as source JAR.
Correctly symlink source JAR during deployment
=> Deploy correct artifact as source JAR

npm/BUILD, npm/assemble.py, npm/rules.bzl, npm/templates/BUILD, npm/templates/deploy.py
Fix #59 
`deploy_npm` is split into `assemble_npm` and `new_deploy_npm` [to be later renamed to `deploy_npm`] for consistency with existing rules (i.e. `assemble_maven`/`deploy_maven`)
- Implement `assemble_npm` which packs package for later deployment
- Implement `new_deploy_npm` which uploads the package built with `assemble_npm`
=> Split deploy_npm to assemble_npm and deploy_npm

WORKSPACE, pip/assemble.py, pip/rules.bzl, pip/templates/BUILD, pip/templates/deploy.py, pip/templates/new_setup.py
Fix #58
`deploy_pip` is split into `assemble_pip` and `new_deploy_pip` [to be later renamed to `deploy_pip`] for consistency with existing rules (i.e. `assemble_maven`/`deploy_maven`)
- Implement `assemble_pip` which packs package for later deployment
- Implement `new_deploy_pip` which uploads the package built with `assemble_pip`
=> Introduce assemble_pip and new_deploy_pip rules

github/rules.bzl, pip/rules.bzl
Previously putting `deploy_github` and `deploy_pip` targets in the same `bazel` package would trigger build error.
Files declared by `deploy_github` and `deploy_pip` had the same name (`_deploy.py`). This PR deduplicates `ctx.actions.declare_file` invocations by prepending invoking target name (which is unique as `bazel` targets should have names unique across the package).
=> Use unique names for files declared by deploy_pip/deploy_github

npm/assemble.py, npm/rules.bzl
Fix building of `assemble_npm` by never executing it remotely
- Previously, `npm pack` (invoked in `assemble.py` - script used by `assemble_npm`) would fail, not being able to resolve `../lib/utils/unsupported.js`. As this only happened on RBE, we now always schedule this action to be executed in the sandbox.
- In the sandbox, `new_package_root` was produced without having `+w` permission — which resulted in not being able to write files into the directory (`npm pack`) or removing it (`shutil.rmtree`)
=> Schedule npm assembly action for local execution

pip/BUILD, pip/repackage.py, pip/rules.bzl
Generated Python sources for Grakn Protocol would need to have replaced package in order to follow the package structure we want. This rule allows for moving Python files to a new package root after they are generated.
Add `python_repackage` rule implementation. Sample usage:
```
python_grpc_compile(
name = "protocol_src",
deps = [
"//keyspace:keyspace-proto",
"//session:session-proto",
"//session:answer-proto",
"//session:concept-proto",
],
visibility = ["//visibility:public"]
)
python_repackage(
name = "protocol_pkg",
src = ":protocol_src",
package = "grakn_protocol"
)
```
=> python_repackage rule implementation

BUILD, README.md, doc_hub.bzl, npm/rules.bzl, pip/repackage.py, pip/rules.bzl
As a measure for easier transition #155 introduced aliases for NPM and PIP deployment rules. This PR renames `new_deploy_npm` and `new_deploy_pip` to have proper names and removes old aliases.
- Rename `new_deploy_pip` -> `deploy_pip`
- Rename `new_deploy_npm` -> `deploy_npm`
- Remove aliases: `deploy_pip`, `deploy_npm`
- Remove unneeded `print` statement in `repackage_python`
- Include `assemble_npm`/`assemble_pip` into docs and regenerate `README.md`
=> Bugfixes: NPM/PIP deploy rules should be named properly

apt/BUILD, apt/generate_depends_file.py, apt/pkg_deb_modified_from_bazel/make_deb.py, apt/pkg_deb_modified_from_bazel/pkg.bzl, apt/rules.bzl
Fix #151
Rules for assembling Debian packages should allow referencing other Bazel workspaces in `depends` attribute.
- Sync `apt/pkg_deb_modified_from_bazel/` with latest `master` of Bazel sources — version that is bundled with `0.26.1` is buggy (bazelbuild/bazel#8518) and we cannot yet use `0.27.0` (bazelbuild/bazel#8659)
- Add optional argument `workspace_refs` to `assemble_apt` — if it's passed, it's used for substitutions in `depends` attribute
=> assemble_apt: allow referencing other bazel workspaces in dependencies

rpm/BUILD, rpm/generate_spec_file.py, rpm/rules.bzl
Fix #152
Rules for assembling RPM packages should allow referencing other Bazel workspaces in `.spec` file
- Add optional argument `workspace_refs` to `assemble_apt` — if it's passed, it's used for substitutions in `spec` file
=> assemble_rpm: allow referencing other bazel workspaces in spec file

pip/assemble.py
We fix assemble.py to no longer require the `--imports` flag to be supplied in order to assemble correctly.
=> Fix assemble_pip

README.md, brew/rules.bzl
Incremental work on #150 for `deploy_brew` rule
- Make `version_file` in `deploy_brew` optional
`bazel run --define version=$(git rev-parse HEAD) //:deploy-brew`
=> Streamlined versioning for deploy_brew

README.md, apt/rules.bzl
Incremental work on #150 for `assemble_apt` rule
- Make `version_file` in `assemble_apt` optional
- Add private rule (`_assemble_apt_version_file`) which exposes version from Bazel command line as a file. Use this file in absence of `version_file` in `assemble_apt`.
`bazel build --define version=$(git rev-parse HEAD) //console:assemble-linux-apt`
=> Streamlined versioning for assemble_apt

README.md, common/java_deps.bzl
Incremental work on #150 for `java_deps` rule
- Make `version_file` in `java_deps` optional
`bazel build --define version=$(git rev-parse HEAD) //console:console-deps`
=> Streamlined versioning for java_deps

maven/_pom_replace_version.py, maven/templates/rules.bzl
Incremental work on #150 for `assemble_maven` rule
- Make `version_file` in `assemble_maven` optional
- Replace `{pom_version}` [placeholder] in `pom.xml`
- Remove `version_file` from runfiles of assemble script — it's not used there
`bazel build --define version=$(git rev-parse HEAD) //console:assemble-maven`
=> Streamlined versioning for assemble_maven

README.md, maven/templates/rules.bzl, npm/rules.bzl
Incremental work on #150 for `assemble_npm` rule
- Make `version_file` in `assemble_npm` optional
- Follow-up to #164: add docs to `version_file` of `assemble_maven`
`bazel build --define version=$(git rev-parse HEAD) //:assemble-npm`
=> Streamlined versioning for assemble_npm

README.md, pip/rules.bzl
Incremental work on #150 for `assemble_pip` rule
- Make `version_file` in `assemble_pip` optional
`bazel build --define version=$(git rev-parse HEAD) //:assemble-pip`
=> Streamlined versioning for assemble_pip

README.md, rpm/rules.bzl
Incremental work on #150 for `assemble_rpm` rule
- Make `version_file` in `assemble_rpm` optional
`bazel build --define version=$(git rev-parse HEAD) //console:assemble-rpm`
=> Streamlined versioning for assemble_rpm

common/rules.bzl
To pass the `tags` property to pkg_tar. The motivation is that I want to signal to our CI runner to skip this in normal presubmit builds.
```python
tags = ["skipci"],
```
Then this target wouldn't be built as part CI. 
This PR passes the `tags` property to pkg_tar as part of assemble_targz.
=> Pass tags to pkg_tar

common/rules.bzl
Follow up to #168, I forgot to pass tags to another rule within assemble_targz
=> Add tags to genrule for assemble_targz

npm/assemble.py, npm/rules.bzl
As migration to latest `@build_bazel_rules_nodejs` is planned, we need to adapt `assemble_npm`/`deploy_npm` to newest rules [while also preserving compatibility with currently-used version].
- Use `@nodejs//:npm` (compatible with both old and new `rules-nodejs`)
- Append `external/nodejs_<platform>_amd64/bin/` to `PATH` when invoking `npm`. Adding `/bin/` and `/usr/bin` is also required to have `bash`/`dirname` available (needed by `npm` script)
=> Prepare for upgrading of @build_bazel_rules_nodejs

npm/templates/deploy.py
Updated `rules-nodejs` change location of `npm`.
Make `PATH` in invoking `npm` in `deploy_npm` same as `assemble_npm`
=> Adapt deploy_npm to latest rules-nodejs

npm/templates/deploy.py
Updated `rules-nodejs` change location of `npm`.
Make `PATH` in invoking `npm` in `deploy_npm` same as `assemble_npm`
=> Quickfix to deploy_npm: properly set PATH

npm/rules.bzl
Fix `deploy_npm` rule implementation
Use `npm` label that's compatible with both `assemble_npm` and `deploy_npm`
=> Fix npm target in assemble/deploy npm rules

gcp/packer.template.json
Fixes graknlabs/grakn-kgms#285
Default image size for GCP deployments should be 20GB to avoid getting a warning
=> Set default GCP image size to 20GB

apt/generate_depends_file.py, rpm/generate_spec_file.py
Fix #178
- `assemble_apt` now takes in `%{version}` - consistent with how it's done in RPM builds
- `assemble_apt` and `assemble_rpm` now verify that for each `%{@dependent_workspace_ref}`, relevant `@dependent_workspace_ref` exists in `workspace_refs`
=> Verify that referenced workspace exists in apt/rpm

maven/_pom_replace_version.py, maven/templates/rules.bzl
Fix #176
`assemble_maven` should support a scenario where `workspace_refs` is not provided by users
* Default to empty `workspace_refs` if no file is provided
=> Make workspace_refs optional for assemble_maven

rpm/rules.bzl
Fix #180 
If `workspace_refs` was passed to `assemble_rpm`, RPM package name would be invalid.
`tag` which is attached to indicate RPM package name should be attached _before_ spec file is modified.
=> Fix RPM package name

brew/templates/deploy.py
To make the `get_distribution_url_from_formula` method in `brew/templates/deploy.py`, compatible with Python 3.
`filter` in Python 3 returns an iterator (not a list) and so we call `next()` on it to get its first element.
=> Makes part of `brew/templates/deploy.py` Python 3 compatible

maven/templates/deploy.py
`deploy_maven` rule broke after we upgraded to `bazel 0.29.1` (and running it with Python 3) with the following exception:
```
File "/home/circleci/.cache/bazel/_bazel_circleci/98db3734c28662e6d9e008d213a17afe/execroot/graknlabs_graql/bazel-out/k8-fastbuild/bin/grammar/deploy.py", line 163, in <module>
pom_updated.write(pom_updated_content)
File "/opt/circleci/.pyenv/versions/3.5.2/lib/python3.5/tempfile.py", line 483, in func_wrapper
return func(*args, **kwargs)
TypeError: a bytes-like object is required, not 'str'
```
Open all temporary files in write-text mode (`wt`) so we could write `str` to it (without first encoding to `bytes`)
=> Fix deploy_maven rule to be compatible with Python 3

maven/templates/deploy.py
`deploy_maven` was failing even when HTTP status code from uploading was successful.
Decode output from `sp.check_output` so `str` is compared with `str`
=> Fix deploy_maven to be compatible with Python 3

brew/templates/deploy.py
Fix `deploy_brew` issues caused by upgrading to Python 3
- invoke `curl` instead of `urllib`
- use natively-available `hashlib` to calculate checksum
=> Bugfix deploy_brew to work with Python 3

brew/templates/deploy.py, maven/templates/deploy.py
`deploy_brew` and `deploy_maven` were non-operational due to incorrect usage of `hashlib`
`hashlib.<algo>` expects `bytes` to calculate checksum of, so we open files in "read binary" (`rb`) mode
=> Bugfix hashlib invocations in deploy_brew and deploy_maven

common/assemble-versioned.py, common/rules.bzl, common/tgz2zip.bzl, common/tgz2zip.py
Partial work on #150
Previously, we had to repack already-built `tar.gz` and `zip` distribution once again due to two reasons:
(1) - archive name doesn't have version in it (`grakn-core-all-linux.tar.gz` instead of `grakn-core-all-linux-1.5.9.tar.gz`)
(2) root folder _inside_ the archive didn't have version in it (`grakn-core-all-linux` instead of `grakn-core-all-linux-1.5.9`)
This pull request addresses (2).
Now, when `--define version=<>` is supplied during build time, it is used to construct root folder name inside the archive.
* `pkg_tar` and `pkg_deb` are now loaded from `@rules_pkg` — version in `@bazel_tools` is going to be deprecated soon
* new rule `_assemble_targz_package_dir_file`: reads `package_file` from attributes and `version` from `--define version=<>` during build time; …
=> Refactor how version is provided for distribution archives

README.md, maven/templates/deploy.py
Partial work on #150
- `deploy_maven` no longer accepts version as command-line argument. Additionally, it no longer modifies `pom.xml` and `jar` which are to be deployed. Instead, it assumes that dependent `assemble_maven` target is already properly versioned by providing `--define version=<VERSION>`
- chore: regenerate docs
=> Refactor how version is provided for Maven deployment

npm/rules.bzl, npm/templates/deploy.py
Partial work on #150
* `deploy_npm` no longer modifies the archive provided by `assemble_npm` if `repo_type` is `snapshot`. Instead, it assumes archive generated by `assemble_npm`  already contains correct version.
* `assemble_npm` now prepends `0.0.0-` if version resembles a commit SHA
=> Refactor how version is provided for assemble_npm rule

maven/templates/deploy.py
Recent changes to `deploy_maven` broke it, causing to throw an exception of these kind:
```
File "/home/circleci/.cache/bazel/_bazel_circleci/b86ecb3d15acddc9ce11cf216fed02f7/execroot/graknlabs_client_java/bazel-out/k8-fastbuild/bin/deploy.py", line 137, in <module>
upload(maven_url, username, password, pom_file_path.name, filename_base + '.pom')
AttributeError: 'str' object has no attribute 'name'
```
This PR addresses this
Treat `pom_file_path` as `str` so exception is not thrown.
=> Bugfix deploy_maven rule

common/java_deps.bzl
Fix #198
Fix `java_deps` rule not being able to handle JARs with same name (even though with different coordinates_
Previously, we were deduplicating Java libraries based on filename even if filename we ended up using was Maven-style. This PR fixes the issue and stores resulting filename for deduplication. Additionally, when a file is excluded, we now print its filename
=> Correctly deduplicate JARs in java_deps

common/rules.bzl
Fix #201
Add `append_version` (`True`) option to `assemble_targz` and `assemble_zip` so it's possible to produce an archive with root folder matching `output_filename` (as opposed to `output_filename-{version}`
=> assemble_targz, assemble_zip: allow to disable version appending

common/tgz2zip.py
Fix graknlabs/grakn#5108
Archives previously produced by `assemble_zip` (underlying rule `tgz2zip`) were not compatible with Windows (Windows Explorer failed to unpack them). As pointed out by experiment, error was caused by having `./` prefix in archive entries. This PR removes the prefix from every ZIP entry.
=> Bugfix tgz2zip to produce archives compatible with Windows

pip/requirements.txt
Recently,  a problem in`assemble_pip` was discovered:
```
File "/home/********/.cache/bazel/_bazel_********/a3bf690c4bacc2f8a31e33bc35f6090b/sandbox/linux-sandbox/191/execroot/graknlabs_client_python/bazel-out/host/bin/external/graknlabs_bazel_distribution/pip/assemble.runfiles/pypi__setuptools_45_0_0/pkg_resources/__init__.py", line 93, in <module>
raise RuntimeError("Python 3.5 or later is required")
RuntimeError: Python 3.5 or later is required
```
Given that we are still using Python 2 to build and test `client-python`, we need to downgrade `setuptools` to a supported version
Depend on exact version of `setuptools` in `pip/requirements.txt`
=> Make dependency on setuptools stricter

maven/templates/rules.bzl
Fix #207
The `assemble_maven` rule seems to be broken with bazel > 1.0.0, failing with the following error:
`object of type 'JavaSkylarkApiProvider' has no field 'outputs'`
This PR aims at fixing that issue.
Use newest attribute for java target info
=> Use JavaInfo instead of the now obsolete java attribute

gcp/packer.template.json, gcp/rules.bzl
Improve configurability of `assemble_gcp` for our newly-discovered usecases
- Make `image_licenses` optional
- Make `source_image_family` configurable
- Make `files` optional
- Make `image_family` configurable
=> Improve configurability of assemble_gcp rule

maven/templates/rules.bzl
Previously, `assemble_maven` (with `package=""`) would fail with this error message:
```
<input file target @io-opencensus-opencensus-contrib-grpc-metrics//jar:io-opencensus-opencensus-contrib-grpc-metrics.jar> doesn't contain declared provider 'MavenPomInfo'
ERROR: Analysis of target '//:assemble-maven' failed; build aborted: Analysis of target '@io-opencensus-opencensus-contrib-grpc-metrics//jar:jar' failed; build aborted
```
Part of the dependency graph:
```
<merged target @org-codehaus-mojo-animal-sniffer-annotations//jar:jar> -> [<input file target @org-codehaus-mojo-animal-sniffer-annotations//jar:org-codehaus-mojo-animal-sniffer-annotations.jar>]
```
`@org-codehaus-mojo-animal-sniffer-annotations//jar` is a target that has `maven_coordinate` tag that we need. However, when …
=> Bugfix assemble_maven: skip leaves representing JAR files

gcp/packer.template.json, gcp/rules.bzl
Previously, `packer` always attached a default service account to GCP instance it created. In case it did not exist it failed with a timeout and cryptic error message.
Allow to create instances without a service account attached (which is fine if you're not doing any calls to GCP APIs during image creation)
=> Allow disabling default service account for assemble_gcp

maven/templates/rules.bzl
Fixing four issues:
1. I'm also using Scala here, which is almost identical in deployment to Java. However, using [scala_library](https://github.com/bazelbuild/rules_scala/blob/master/docs/scala_library.md) with `assemble_maven` doesn't work. 
2. The POM file name is hard-coded (`pom.xml`). Because we use both Scala and Java in the same BUILD file, the file was getting overwrite. #215 
3. Targets that have only the `files` attribute failed to run because the provider return `srcjar` when there's isn't any defined. #214 
4. `target_coordinates` is hard-coded to `[0]`, and it's not working on all cases.
There's another thing to consider here it seems. When using exports, I had problem with:
target_string = target[JavaLibInfo].target_coordinates.to_list()[-1]
The first element in the array …
=> Adding Scala and multiple POM files support.

BUILD, README.md, azure/BUILD, azure/packer.template.json, azure/rules.bzl, doc_hub.bzl
Implement a rule for deployment Microsoft Azure machine images
Implement `assemble_azure` macro. Sample usage:
`load("@graknlabs_bazel_distribution//azure:rules.bzl", "assemble_azure")`
```
assemble_azure(
name = "assemble-azure-project",
install = "//:install.sh",
files = {
"//:assemble-linux-targz": "archive.tar.gz",
},
image_name = "...",
resource_group_name = "..."
)
```
=> Implement assemble_azure rule

azure/packer.template.json
In order to improve compatibility and stay up-to-date, Azure images produced by `assemble_azure` now are based on latest Ubuntu LTS at the time, 20.04. 
Change base Azure image to Ubuntu Server 20.04 LTS
=> Upgrade Azure base image to Ubuntu 20.04

BUILD, README.md, distribution/BUILD, distribution/rules.bzl, distribution/templates/BUILD, distribution/templates/deploy.py, doc_hub.bzl
Since many of our tests rely on separately executable artifacts (mainly grakn) that should not share any dependencies with the tested artifact, we want to be able to deploy versioned snapshot and release artifacts built for specific commits with the correct versions of dependencies so that tests can properly run against a static version that will not change due to overlaid bazel dependencies.
This requires writing a bazel rule that will publish some archive/file to a raw repository, which is the goal of this PR.
- Added `deploy_distribution` rule that publishes a single artifact to a raw repo.
=> Add deploy_distribution rule

pip/rules.bzl
Currently, when attempting to assemble `kglib`, `assemble_pip` would (depending on a platform) either fail or produce an incorrect Python package.
`assemble_pip` would no longer assume `pypi`/`external` markers will be at _start_ of package or file name, but that they might be in any part of it
=> Fix assemble_pip rule

maven/templates/rules.bzl
Add support for source jars generated by the `kt_jvm_library` rule.
Small change to allow the source jar to end with `-sources.jar`.
https://github.com/bazelbuild/rules_kotlin/issues/324
=> add '-sources.jar' as potential srcjar

BUILD, README.md, WORKSPACE, bazelbuild_rules_python-export-requirements-bzl-for-stardoc.patch, common/dependencies.bzl, doc_hub.bzl, maven/BUILD, npm/rules.bzl, npm/templates/deploy.py
We found that skydoc was forcing us to depend on an old version of rules_nodejs, preventing us from upgrading elsewhere. This issue is described in detail in #251.
The goal of this PR is to remove our dependency on forks of `skydoc` and `bazel` by applying a patch to `rules_python` that allows the most recent version of `stardoc` to work.
- Apply a patch to `rules_python` (which is now directly imported and has been updated.)
- Updated `rules_nodejs`.
- Apply the "official" workaround for `stardoc`, which is to include the sources of files that our rules depend on in the stardoc rule as source dependencies.
=> Fix old dependency on Skydoc, update rules_nodejs

npm/rules.bzl
To correctly run `assemble-npm` on both local and RBE (even though this target is NOT rbe-compatible, as it produces directories), we modify the path that is passed into the `assemble-npm` python `assemble.py` implementation.
* Use target label package instead of target[0].path
=> Make `assemble-npm` function correctly when run with RBE

npm/assemble.py, npm/rules.bzl
Prior changes #255  and #254 attempted to make RBE fail gracefully in the `assemble-npm` rules. However, this ended up not working and this PR reverts the previous PRs.
* Remove `local: 1` requirements in `assemble-npm` rule implementation
* revert change to obtain contents npm package from `ctx.attr.target.label.package` to `ctx.files.target[0].path`
* Add to doc that the `assemble-npm` rule cannot be run in RBE
=> Update npm rules - revert use of target package path

maven/rules.bzl
Fix `assemble_maven` to allow deploying `java_import` targets
Currently, when trying to deploy `java_import` targets, `assemble_maven` fails with this error:
```
File "/home/vmax/work/graknlabs/alex-debug/dependencies/library/rocksdbjni/BUILD", line 59
assemble_maven(name = 'assemble-maven')
File "/home/vmax/.cache/bazel/_bazel_vmax/479536ed392db81ef53584b0e6cda650/external/graknlabs_bazel_distribution/maven/rules.bzl", line 359, in _assemble_maven_impl
output.source_jar.basename
'NoneType' value has no field or method 'basename'
```
=> Account for cases where source JAR doesn't exist

maven/rules.bzl, maven/templates/deploy.py
Follow-up to #262 which tweaks `deploy_maven` to access artifacts without source jars
Gracefully handle absence of source JAR while deploying
=> Allow absent srcjar in deploy_maven

README.md, common/java_deps.bzl
To allow Grakn 2.0 to output rocksdb-dev to lib/dev and rocksdb-prod to lib/prod when building a Grakn distribution.
Firstly, we need to be able to target Maven packages using `java_deps`. We add support for this by looking through both `ctx.attr.target.data_runfiles.files` and `ctx.attr.target.files`.
We also add support for `java_deps` to have output path overrides. When a JAR matching the given pattern is found, it is deployed to the folder specified in the override, instead of the default output folder.
=> Allow java_deps to target Maven packages and support overrides for the output path

maven/templates/deploy.py
Fix incorrect error message referencing the wrong regex when trying to deploy an invalid release version to a maven repository:
```
An artifact uploaded to a release repository must have a version which complies to this regex: ^[0-9|a-f|A-F]{40}$
```
Corrects error message to:
```
An artifact uploaded to a release repository must have a version which complies to this regex: ^[0-9]+.[0-9]+.[0-9]+$
```
=> Fix error message for incorrect maven version

github/rules.bzl, github/templates/deploy.py
We have added a `draft` parameter to `deploy_github`. If it is set to `True`, the rule will create a release that is marked as draft. When set to `False`, the release will be immediately published.
This is an improvement of the existing behaviour, in which you can only create a draft release.
- Implement the `draft` field
- Refactor the rule and `deploy.py` template
=> Adds a parameter in deploy_github that allows for creating both a draft as well as a published release

azure/packer.template.json, azure/rules.bzl
There is a need to deploy custom Azure images that are not based on Ubuntu 20.04. This PR makes image publisher, sku and offer configurable.
Make it possible to configure `image_publisher`, `image_offer` and `image_sku`; leave the old hardcoded options are default for backwards compatibility.
=> assemble_azure: allow for custom base image

maven/templates/deploy.py
Allow snapshot releases with the standard -SNAPSHOT naming convention.
Update the snapshot regex. I've verified the change.
Closes #230
=> allow conventional SNAPSHOT maven releases

README.md, pip/assemble.py, pip/rules.bzl, pip/templates/BUILD, pip/templates/setup.py
Currently, there are a couple of tech debt items in `assemble_pip` that need to be addressed:
* `setup.py` template is still named `new_setup.py` which is a leftover from old migration
* `assemble_pip` accepts dependencies list as string list **but** the actual dependencies (Bazel-wise) are pulled from `requirements.txt`. This makes it very easy to make a mistake of forgetting to upgrade the version passed to `assemble_pip` which would result in a malfunctioning released package. Instead, we should only have one source of truth about what other packages this packages depends on - and that would be `requirements.txt`
* Rename `new_setup.py` to `setup.py`
* Make `assemble_pip` accept `install_requires_file` (single file) instead of `install_requires` (string list).
* Regenerate docs in …
=> Read package requirements from a file

.grabl/automation.yml, README.md, pip/assemble.py, pip/rules.bzl
In order to keep the naming consistent, we need to rename `install_requires_file` attribute to `requirements_file` in `assemble_pip`. Additionally, syntax of Grabl was changed and we need to replace `machine:` with `image:`
* Rename `install_requires_file` to `requirements_file` in `assemble_pip` and regenerate the docs
* Replace all `machine:` usages with `image:`
=> Change naming in assemble pip

github/templates/deploy.py
Sometime, release notes on GitHub need to reference the actual version that's being deployed ("install version X.Y.Z by executing this command") by referencing it with template argument "{version}"
Replace the `{version}` in release description with the git tag being deployed
=> deploy_github: fill in version

artifact/rules.bzl
Fix `artifact_extractor` rule not working under Mac and simplify the implementation
Unify the script for unpacking tar and zip archives into one and detect the archive type inside of it (instead of relying on the filename)
=> Fix artifact_extractor rule

pip/assemble.py
Currently, adding `--extra-index-url` into `requirements_file` of `assemble_pip` would throw the following error:
```
File "<stdin>", line 1, in <module>
File "/usr/lib/python3.8/distutils/core.py", line 225, in run_setup
raise RuntimeError(("'distutils.core.setup()' was never called -- "
RuntimeError: 'distutils.core.setup()' was never called -- perhaps './setup.py' is not a Distutils setup script?
```
It stops users from depending on packages from repositories other that regular PyPI.
Allow users of `assemble_pip` to have `--extra-index-url` line in `requirements.txt` (by ignoring it)
=> Fix assemble-pip to skip --extra-index-url lines

.grabl/automation.yml
Fix `build` by adapting to newest syntax of Grabl's `automation.yml`
=> Adapt to new Grabl automation.yml syntax

pip/repackage.py, pip/rules.bzl
Our `python_repackage` rule failed to replace package names if they were nested packages. We fixed that by requiring the user to specify the source package name in the rule itself. The parameters to `python_repackage` are now: `src`, `src_package`, and `py_package_add_prefix`.
Make python_repackage work with nested packages
=> Make python_repackage work with nested packages

pip/templates/deploy.py
Currently `deploy_pip` fails in runtime with `ModuleNotFoundError: No module named 'twine'` error
Update the `sys.path` such that it no longer fails
=> Update deploy_pip rule implementation

github/templates/deploy.py
Allow overriding artifacts in existing release.
- Specify `-replace` argument instead of `-delete` when invoking ghr.
=> Allow overriding artifacts in existing release

brew/templates/deploy.py
Allow running `deploy_brew` with Python 2 being active system-wide
Fix "TypeError: list object is not an iterator" error by making an iterator out of a list
=> Fix deploy_brew rule to be compatible with Python 2

brew/templates/deploy.py
Fix deploying non-ZIP (e.g. `.dmg` as in Grakn Workbase) targets to Homebrew repositories
Detect extension of the file and only validate ZIP correctness if it's in fact a ZIP archive.
=> Fix deploy_brew rule for non-zip targets

BUILD, bazelbuild_rules_pkg-fix-tarfile-format.patch, common/deps.bzl
Patch `rules_pkg` in order for us to be able to build snapshot Console distribution with long filenames.
Patch `rules_pkg` such that archives with long filenames are correctly produced
=> Fix producing .tar.gz archives with long filenames

maven/BUILD, maven/Repackager.kt, maven/rules.bzl
Allow merging JARs without Maven coordinates into a JAR being assembled by `assemble_maven`
Merge dependant non-Maven JARs into the deployed JAR
=> Improve assemble_maven to support merging JARs

maven/new_rules.bzl
Allow deploying Maven artifacts produced by new Maven rules.
Fix passing artifact id and version of the deployed artifact; skip printing the aggregated dependency info of the target.
=> Fix not being able to deploy Maven artifacts

README.md, maven/JarAssembler.kt, maven/rules.bzl
Allow assembling source JARs where sources or them come from mixed sources (both generated and hand-written).
Modify `JarAssembler` to place files inside of source JAR according to the `package` statement in the source file. This allows us to produce always-correct source JARs as well as eliminates the need for passing `source_jar_prefix`
Fix #298
=> Fix assemble_maven to produce valid source JARs

maven/JarAssembler.kt
Make JARs produced by `assemble_maven` correct
Put `ZipEntry` into the archive _before_ writing file contents
=> Fix assemble_maven to produce correct JARs

README.md, common/targz/rules.bzl, common/tgz2zip/rules.bzl, common/tgz2zip/tgz2zip.py, common/zip/rules.bzl
Ensure behaviour of `assemble_zip` is consistent with `assemble_targz` by relying on it to do the actual work.
Fix #306 
* Rely on `assemble_targz` for `assemble_zip` implementation
* Modify `tgz2zip` to not modify the archive structure and just do the repacking
=> Refactor assemble_zip rule to be consistent with assemble_targz

brew/templates/deploy.py
Allow `deploy_brew` to fail earlier with a better error message
Prevalidate the existence of environment variable that `deploy_brew` expects
=> Validate environment variables for deploy_brew

README.md, azure/packer.template.json, azure/rules.bzl
Allow users to generate Azure images with increased OS disk size.
Take in `disk_size_gb` argument and pass it down to Azure template. Example usage:
```
assemble_azure(
name = "assemble-vaticle-ubuntu",
install = "//infrastructure/common/images:ubuntu",
image_name = "vaticle-ubuntu-{{user `version`}}",
resource_group_name = "grabl-common",
files = {
"//automation/job/timeout:job-timeout_deploy.jar": "job-timeout.jar"
},
disk_size_gb = 60,
)
```
=> Allow passing custom disk size when generating Azure images

common/tgz2zip/tgz2zip.py
Make archives assembled by `assemble_zip` rule unpackable on Windows.
Normalize paths when assembling ZIP archives, which means `./typedb-all-windows/typedb.bat` would become `typedb-all-windows/typedb.bat`
Fix #315
=> Normalize paths when assembling ZIP archives

maven/templates/deploy.py
Fix `SNAPSHOT` uploads for Artifactory repositories. Due to the order of upload, Artifactory would expand the `SNAPSHOT` differently for the POM and JAR artifacts, resulting in mismatched artifacts:
You can see that the POM version `SNAPSHOT` resolved to `20210916.163241-1` and the JAR version `SNAPSHOT` resolved to `20210916.163242-2`. Furthermore, the POM checksum uploads would fail as they would be attempted to upload for the latest SNAPSHOT, `20210916.163242-2`, which wouldn't exist:
```
Target file to set checksum on doesn't exist: MySnapshotRepo:com/example/bazel/plugin/0.0.9canary13-SNAPSHOT/plugin-0.0.9canary13-20210916.163242-2.pom
```
Uploading the JAR artifact first fixes this issue and didn't affect uploads to release repositories.
=> Fix `SNAPSHOT` uploads for Artifactory repositories

maven/PomGenerator.kt
Some maven libraries don't have have further dependencies, which caused assemble_maven and pom_generator to fail. This change allows us to handle empty lists of maven dependencies during POM generation.
* Discover that the `--target_deps_coordinates` option that split by `;` automatically produces a list with an empty element when given an empty string --  we want to get an empty list, rather than a list with an empty element
* Implement the above change by manually processing the provided list
=> Allow empty maven deps_coordinates

platform/jvm/BUILD, platform/jvm/JVMPlatformAssembler.kt, platform/jvm/Shell.kt, platform/jvm/rules.bzl
The `assemble_jvm_platform` rule was failing to compile due to some broken changes that went in, so we fixed them.
- Undelete config_setting: apple-code-sign (I thought it was unused but it is actually used in typedb-studio)
- Correctly unpackage the JDK on Mac/Linux using `tar`, not `jar`
=> Platform JVM assembler fixes

crates/CrateAssembler.kt
Currently, it's impossible to place `assemble_crate` targets at the root package level (`//...`) since doing so would fail at build time with `NullPointerException`.
Correctly obtain the parent folder for crate roots located at the root of Bazel workspace
=> Allow assemble_crate packages to be created in root Bazel package

maven/deps.bzl
We had previously deleted maven_artifacts (without versions) because of an incorrect assumption that they were unused - we are now bringing them back (they are used when setting up external repositories to depend on Maven packages via Bazel)
- Add maven_artifacts without versions
=> Add maven_artifacts without versions

README.md, crates/rules.bzl
Allow user to not have to specify duplicate information about the dependencies of the crate package being deployed and instead gather all the info automatically from Bazel.
Fix #323
=> Automatically collect crate dependencies

maven/BUILD
Use proper class names for jar assembler & pom generator
Restore class names to properly working ones
=> Fix class naming for Java builder targets

npm/deploy/Deployer.kt
We fixed a bug where `deploy_npm` would fail to authenticate because it was passing the registry URL in an incorrect format to the `.npmrc` file.
Pass registry URL in correct format in deploy_npm
=> Pass registry URL in correct format in deploy_npm

npm/deploy/Deployer.kt
The auth token passed to the `deploy_npm` rule is now masked in the rule's output logs.
Mask auth token parameter when running deploy_npm
=> Mask auth token parameter when running deploy_npm

npm/assemble/assemble.py
To fix issues with running the assembly rules with a m1 mac
- Adds the correct architecture folder under the `PATH` search
=> Make assemble_npm support M1 architecture

maven/JarAssembler.kt, maven/rules.bzl
Support bundling local `java_import` deps that may or may not conflict when bundled (#335).
The use case here is around bundling JARs for different platforms and potentially having a multiplatform JAR as well. 
1. Support for bundling `java_import` targets
Add a bit more graceful handling for dependencies that don't have a `maven_coordinates` tag. Originally, the aggregation would attempt to just pull directly from `target[OutputGroupInfo].compilation_outputs` without checking to see if it actually existed, resulting in the error from #335. Now, that logic is guarded in checking that `compilation_outputs` is truthy. Additionally, the source JAR is optional in `java_import`, so I added some safety against adding the source JAR when it doesn't exist.
Just that alone didn't fix `java_import` …
=> Better support for multiplatform Maven publications w/ local JARs

.factory/automation.yml, apt/generate_depends_file.py, apt/templates/deploy.py, artifact/templates/deploy.py, brew/templates/deploy.py, common/assemble_versioned/assemble-versioned.py, common/java_deps/java_deps.py, common/tgz2zip/tgz2zip.py, github/templates/deploy.py, maven/templates/deploy.py, npm/assemble/assemble.py, packer/templates/deploy_packer.py, pip/assemble.py, pip/repackage.py, pip/replace_imports.py, pip/templates/deploy.py, rpm/generate_spec_file.py, rpm/templates/deploy.py
We now use the command `python3` explicitly instead of `python`. As all of our code is written in Python 3 and the command `python` is ambiguous for historical reasons, this is more in line with our current approach in using java and bazel. That is, we rely upon the image that is provided to specify the appropriate version of these binaries rather than doing so ourselves.
We have changed every line specifying 
```
#!/usr/bin/env python
```
to
```
#!/usr/bin/env python3
```
=> Explicitly use python3

crates/rules.bzl
We made `assemble_crate`, by default, generate a crate version equal to the `version` field of its `target` (i.e. the `rust_library`, etc. being assembled) 
Previously if we ran `deploy_crate` with no `version_file` or `--version` argument specified, it would deploy crate version `0.0.0`. Now, we deploy whatever version is specified in `assemble_crate`'s `target` (which itself defaults to `0.0.0` if unspecified)
=> Make `assemble_crate` version default to its target's version

crates/rules.bzl
We now prepend `0.0.0` to the version of the crate assembled by `assemble_crate` if it looks like a commit SHA (i.e: is a snapshot crate)
Deployment of snapshot distributions to other repos such as PyPi depends on logic that checks the length of the version, and if it's 40, we assume it's a commit SHA (hence a snapshot crate) and prepend 0.0.0 to it.
We now do the same for crates.
=> Prepend 0.0.0 to the version of `assemble_crate` if it looks like a commit SHA

NOTICE, common/Logging.kt, common/assemble_versioned/BUILD, common/checksum/BUILD, common/generate_json_config/BUILD, common/java_deps/BUILD, common/targz/BUILD, common/tgz2zip/BUILD, common/util/FileUtil.kt, common/util/PropertiesUtil.kt, common/util/SystemUtil.kt, common/workspace_refs/BUILD, common/zip/BUILD, common/zip/rules.bzl, crates/CrateAssembler.kt, crates/CrateDeployer.kt, maven/JarAssembler.kt, maven/PomGenerator.kt, npm/deploy/DeployNPM.kt, npm/deploy/Deployer.kt, platform/jvm/Main.kt, platform/jvm/Options.kt
We update the copyright header year to 2022.
Replace the year 2021 with 2022 in each copyright header.
=> Bump copyright year to 2022

maven/PomGenerator.kt, maven/rules.bzl
Support publishing to Maven Central again. Was originally done in #133, but the `developers` tag was never migrated to the maven rule rewrite in #296.
Add an optional `developers` attribute to `assemble_maven` rule as a `string_list_dict`. Developers can be described as such:
```
developers = {
"sugarmanz": ["name=Jeremiah Zucker", "email=zucker.jeremiah@gmail.com"],
"adierkens": ["name=Adam Dierkens"],
}
```
And will be populated as:
```xml
<developers>
<developer>
<id>adierkens</id>
<name>Adam Dierkens</name>
</developer>
<developer>
<id>sugarmanz</id>
<name>Jeremiah Zucker</name>
<email>zucker.jeremiah@gmail.com</email>
</developer>
</developers>
```
=> [assemble_maven] add developers tag support for pom (to support Maven Central)

pip/assemble.py, pip/rules.bzl, pip/templates/setup.py
Produce pip distributions that aren't available to python 2 users (or any arbitrary python version)
Adds a `python_requires` attribute to `assemble_pip` passed through to `setup.py` as defined in https://packaging.python.org/en/latest/guides/distributing-packages-using-setuptools/#python-requires
For example,
```py
assemble_pip(
...
python_requires = ">=3",
)
```
should produce a setup.py that makes the package unavailable to users of python 2.
Also fixes an error in the assemble script if the package is empty.
=> [assemble-pip] Add python_requires to limit package to python 3 only

crates/CrateAssembler.kt
We add [lib] section to the crate manifest, specifying the library root.
=> Add library section to generated Cargo.toml

apt/rules.bzl, brew/rules.bzl, maven/rules.bzl, npm/deploy/rules.bzl, pip/assemble.py, pip/requirements.txt, pip/rules.bzl, pip/templates/deploy.py, rpm/rules.bzl
The `deploy_pip` rule was modified by #368 to allow deploying wheels and targz packages to repositories provided by a `pypirc` file. However, this broke this repository's consistent design: every `deploy_*` rule provides all possible repositories to upload to (eg. using `snapshot` or `release`), then selects which one to deploy to at run time using arguments.
This PR revert some changes to the `deploy_pip` rule to make it conform to this consistent design. We also fix some bugs during the upload process. 
Finally, we extend the doc strings for each of the deploy rules to indicate how to select the repository to deploy to. 
The `deploy_pip` rule is changed to take multiple different destination repositories to upload to. These are provided, as before, using the existing `snapshot` or …
=> Fix pip deployment and extend deploy rule doc strings with usage

npm/deploy/Deployer.kt, npm/deploy/Options.kt
As of January 2023, the `deploy_npm` using npm v8.x rule appears to stop working with pre-generated auth tokens for Sonatype repositories. However, we discover that the simpler mechanism of using base64 encoded username/password does work.
Using the base64 encoded authenciation is also [recommended](https://help.sonatype.com/repomanager3/nexus-repository-administration/formats/npm-registry/npm-security#npmSecurity-AuthenticationUsingBasicAuth) by Sonatype, we can successfully deploy.
However, the deployment to centralised NPM repositories may still require using token-based authentication. As a result, we extend the deployment rule to support both username/password or token-based authentication.
This issue was last worked on in https://github.com/vaticle/bazel-distribution/pull/330
* …
=> Extend NPM deployment with password or token-based deployment

pip/rules.bzl, pip/templates/deploy.py
The new functionality introduced in #368 to deploy wheels did not introduce the right naming convention for wheels - PyPi for example will decline packages not naming according to the [PIP491](https://peps.python.org/pep-0491/).
This PR restricts the `assemble_pip` to only produce `py3` type archives, which can then be deployed with the required naming convention.
* Restrict `assemble_pip` to only allow Python-3 compatibility
* `deploy_pip` produces wheels that conform to `{name}-{version}-{pyversion}-{abi}-{platform}` by hardcoding it to `{name}-{version}-py3-none-any`
=> Use PEP491 naming conventions for wheel deployments to pip

common/java_deps/rules.bzl
In the collection of transitive maven dependencies for Java, we ignore all JARs available in the JDK that is chosen. This is extended to allow ignoring of JARs coming from the remote JDK or the local JDK. Use of the remote JDK in Bazel ensures hermiticity in some systems, which is a desirable option to have.
* Allow java-deps to skip jars included in either the remote or local JDK
=> Allow java deps to filter out remote or local JDK jars

maven/PomGenerator.kt, maven/rules.bzl, maven/templates/deploy.py
We update deployment and assembly rules to be invokable on Windows, and to support per-platform profiles in pom.xml.
Per-platform overrides expects a dict of bazel labels to a JSON-encoded dictionary of platform to maven coordinates.
Supported OS: windows, linux, mac
Supported architectures: x86_64, aarch64
Ex.:
```
assemble_maven(
...
profile_overrides = {
":bazel-dependency": json.encode({
"windows-x86_64": "org.company:dependency-windows-x86_64:{pom_version}",
"linux-aarch64": "org.company:dependency-linux-aarch64:{pom_version}",
"linux-x86_64": "org.company:dependency-linux-x86_64:{pom_version}",
"mac-aarch64": "org.company:dependency-macosx-aarch64:{pom_version}",
"mac-x86_64": "org.company:dependency-macosx-x86_64:{pom_version}",
})
}
)
```
- improve portability of maven assembly …
=> Update Maven rules to support platform profiles and Windows deployment

artifact/rules.bzl
The updated `rules_pkg` (updated in https://github.com/vaticle/bazel-distribution/pull/382) packages `tar.gz` files without a leading `./` path. The artifact extractor therefore only needs to strip one layer from `tar.gz` files built by the `assemble_targz`, instead of two.
Strip one layer of directories from `tar.gz` files while extracting TypeDB distributions.
=> Update artifact extractor to be compatible with updated rules_pkg

crates/CrateAssembler.kt, crates/CrateDeployer.kt, crates/rules.bzl, crates/templates/deploy.sh, maven/PomGenerator.kt
Assembling a Rust crate failed to convert external bazel workspace dependencies into Crate depedencies using the external dependency's version, as specified by workspace refs. We now use workspace references to correctly convert external rust library dependencies into crate dependencies, with version specifiers.
In addition, we now package README and LICENSE files into the generate crate.
* Experimental: delete `metadata` generation from Crate assembly, it may not be required
* Add workspace refs to crate assembly, which converts external bazel workspace dependencies into correctly versioned crate manifest dependencies
* add license and readme's into generated crate tarballs
=> Assemble external workspace dependencies into Cargo dependencies

brew/rules.bzl, brew/templates/deploy.py, common/checksum/rules.bzl, platform/BUILD, platform/constraints.bzl, platform/jvm/rules.bzl
We add limited support for multiple homebrew artifact URLs with corresponding checksums.
- revert the checksum rule so that it computes the sha256 of the entire file rather than unzipping the file and checksumming its contents;
- move the platform configs from dependencies into here to break the circular dependency.
=> Support architecture specific brew formulae

apt/rules.bzl
We refactor the `assemble_apt` rule to rely on new-style `pkg_rules` conventions: we add symlinks via `pkg_symlink`, and files via `pkg_files`, and archives to expand and embed via `pkg_tar`.
* Refactor `assemble_apt` to use new packaging rules from `pkg_rules`
=> Refactor apt packaging to use new pkg_rules rules

platform/jvm/AppleCodeSigner.kt, platform/jvm/CommandLineParams.kt, platform/jvm/JVMPlatformAssembler.kt, platform/jvm/MacAppNotarizer.kt, platform/jvm/Options.kt, platform/jvm/rules.bzl
We switch to using `jpackage` to sign the AppImage rather than signing the files manually. We also switch from `altool`, which is now deprecated for notarization, to `notarytool`. 
JVM17 `jpackage`, unlike before, always attempts to sign `Home/runtime` when assembling an AppImage. In the absence of credentials, it uses ad-hoc signing, in the process stripping the Oracle signatures from the JVM runtime files, which causes the notary to reject the submitted app. This behaviour does not appear to be configurable outside of being able to provide credentials to the signing process, which we now do instead of running `codesign` ourselves.
The `altool` deprecation appears to have been a red herring, but upgrading to `notarytool` was past due regardless.
=> Update MacOS DMG signing and notarization process

common/targz/rules.bzl
We introduce `targz_edit()`, a rule that allows us to modify a targz. Currently, this rule only supports the `strip_components` argument.
=> targz_edit: modify contents of targz

crates/CrateAssembler.kt, maven/PomGenerator.kt, maven/rules.bzl, npm/assemble/rules.bzl, pip/rules.bzl
We add support for repository-specific prerelease versioning, currently limited to "rc" (release candidate).
This change ensures the following format:
- `{version}-rc{number}` in maven packages, npm packages, and crates (following [SemVer 2.0.0 spec](https://semver.org/spec/v2.0.0.html));
- `{version}rc{number}` in pip packages (see [Python Packagin User Guide :: Version specifiers](https://packaging.python.org/en/latest/specifications/version-specifiers/#public-version-identifiers))
Drive-by: ensure semver compatibility for snapshot releases in crates and maven by prepending `0.0.0-` to the git commit SHA.
=> Release candidate support

maven/templates/deploy.py
Fix regression introduced in #397: prepending `0.0.0-` to the commit SHA for snapshot assembly broke the validation in the deployment script, which expects either bare SHA or any string ending with `-SNAPSHOT`. We now require either a major.minor.patch version with the SHA at the end, or any string ending with `-SNAPSHOT`.
=> Fix maven pre-deploy snapshot version validation: require SemVer-SHA

common/rules.bzl, common/zip/rules.bzl
We add a new common utility rule that allows the user to unzip a zip archive containing a single file and give that file a new name.
=> Add unizp_file utility rule

common/targz/rules.bzl
We add the options to exclude files and directories that match glob patterns from the edited .tar.gz archive.
=> targz_edit: add support for glob exclusion patterns

artifact/rules.bzl, artifact/templates/deploy.py
We fix two issues in artifact deployment rules:
1. The `version_file` argument was ignored in favor of the `version` environment variable. The behavior is now in line with the rest of rulesi n this repository.
2. Snapshot version validation was overly strict and only permitted versions that were exactly SHA1. We now require that a snapshot artifact version _ends_ in SHA1.
=> Artifact deployment: use version_file, fix version validation

apt/rules.bzl, apt/templates/deploy.py, common/uploader/cloudsmith.py
The version is added to the uploaded filename of apt packages when being deployed. Without this, Cloudsmith's APT fetch ends up corrupted and downloads the wrong package, when multiple packages share the same file name across different versions.
* Adds a line in the deployment script to upload `package.deb` as `package_version.deb` on cloudsmith
=> Add version to uploaded apt package filename

doc_hub.bzl, nuget/rules.bzl
We fixed the build issues with the doc target, that appeared because of the `cpp` dir renaming in[ the previous PR](https://github.com/vaticle/bazel-distribution/pull/406), and some code style in the meantime.
=> Fix docs target build

WORKSPACE, gcp/packer.template.json, packer/deps.bzl
We've upgraded Packer to 1.8.3 and increased the GCP packer image disk size to 50GB.
As above.
=> Upgrade Packer and increase GCP packer image disk size

crates/CrateAssembler.kt, maven/PomGenerator.kt, maven/rules.bzl, maven/templates/deploy.py
We resolve issue #380 by trimming input `version` values from `VERSION` files for `maven` and `crate` artifacts assembly rules. It solves the problem of `VERSION` files being passed as `version_file` to the respective rules after being formatted to have an additional empty line in the end, which is a standard convention for files and a common IDE setting, or just being formatted incorrectly while containing a valid value.
From now on, `VERSION` files passed into `assemble_maven` and `assemble_crate` can have any leading and trailing whitespaces.
We add `trim()` calls for all the `.kt` scripts reading `version` files. This behavior used to exist for many `.py` scripts (with `strip()` for `Python` `string`), but these places were left forgotten (and not noticed by us as we use `--define …
=> Remove leading and trailing whitespaces from VERSION files for crate and maven assembly rules

apt/generate_depends_file.py, apt/rules.bzl
Dependency declarations in `assemble_apt` (`depends`) are now optional. This allows for the publishing of APT packages that have no dependencies.
- Make `--deps` optional in the Python script that powers `assemble_apt`
- Make the `assemble_apt` rule not crash with `depends` unspecified
=> In `assemble_apt`, make dependency declarations optional

npm/deploy/Deployer.kt
We update npm_deploy to use the provided path for `npm` directly.
It appears that the `env` `PATH` variable gets ignored by `Shell`, so the `npm publish` invocation defaults to the system `npm`, which can lead to unexpected results.
=> npm deployer: use the provided npm path directly

pip/rules.bzl
We add `pip` packages version reformatting from our (TypeDB) version conventions to [the python conventions](https://packaging.python.org/en/latest/specifications/version-specifiers/#version-specifiers) for `alpha` and `beta` releases.
In addition to already existing `-rc` -> `rc` reformatting, we add:
* `-rc-` -> `rc`
* `-alpha-` -> `a`
* `-alpha` -> `a`
* `-beta-` -> `b`
* `-beta` -> `b`
To support multiple variants for better reusability.
=> Add reformatting for alphas and betas

common/shell/Shell.kt, platform/jvm/AppleCodeSigner.kt, platform/jvm/JVMPlatformAssembler.kt, platform/jvm/MacAppNotarizer.kt
- We remove the `skipIfSigned` functionality from the `AppleCodeSigner`
- We add verbose logging to `xcrun` calls if it is enabled
We've concluded that it is not the responsibility of a maintainer of an open-source library to sign their code for MacOS installers, as such we want to sign these packages ourselves. This may cause us to assume responsibility for issues in our application caused by these packages; this seems reasonable.
We have previously encountered issues when releasing `typedb-studio` due to a package that was signed, but not specifically for MacOS installers, failing Apple's checks. As such, we want to sign *all* packages captured by our `deepSignJarsRegex` - not just unsigned ones. This ensures that all signatures are valid.
However, we still value the `deepSignJarsRegex` …
=> Improve Apple code signing

brew/templates/deploy.py
Updates  type hints in the brew deployment script to use Dict instead of dict
Updates  type hints in the brew deployment script to use Dict instead of dict
=> Update type hint in brew deployment script
