maven/BUILD
maven/deployment_rules_builder.py
maven/templates/rules.bzl

Adapt to using `jarjar_library`

Fix Maven rules to support jarjar_library targets

---

pip/templates/deploy.sh

Prevented Python packages from deploying

Use correct folder for Pygments package

---

npm/templates/deploy.sh
pip/templates/deploy.sh

* Support custom registries for NPM on Sonatype
* Support more repo keys for PyPI (will be defined in `@graknlabs_grakn_core`)

Improvements in supporting custom Sonatype repos for NPM and PyPI

---

distribution/rules.bzl

Fixes second part of graknlabs/grakn#4803
Removed unneeded files from local JDK from distribution which also solves the problem (duplicated files were there)

Remove unneeded files from distribution

---

WORKSPACE
github/deploy.py
github/rules.bzl

Fixes #39
Adds `deploy_github` rule

Implementation of deploy_github rule

---

common/rules.bzl

Fixes #62
* removes default value for `java_deps_root` attr
* skips duplicated files

Fix implementation of java_deps

---

maven/templates/rules.bzl

Un-break implementation of `assemble_maven`
Removes generation of deployment script (which is never used) from a deployment script template (which isn't there anymore)

Bugfix assemble_maven: we don't use shell script anymore

---

rpm/pkg_rpm_modified_from_bazel/make_rpm.py
rpm/templates/deploy.sh

Fix RPM packaging/deployment issue
- Specify target OS in `pkg_rpm`
- Rename package on deployment

Bugfix deploy_rpm implementation: specify target OS, name package properly

---

apt/templates/deploy.sh
brew/templates/deploy.py
maven/templates/deploy.py
npm/templates/deploy.sh
pip/templates/deploy.sh
rpm/templates/deploy.sh

Adapt to latest naming scheme
Credential env vars removed

Rename credential env vars

---

rpm/rules.bzl

Allow building RPM packages without files (i.e. `grakn-core-all` which only declares dependency on `console` and `server`)
Make `installation_dir` optional and skip generating `tar` if it's `None`

Make installation_dir an optional param to assemble_rpm

---

common/tgz2zip.py

Addresses bug described in graknlabs/grakn#5044
Set `S_IFREG` ('regular file') flag to files inside of the archive. While previously we copied permission bits from `tar`, it did not have such a flag (so it would be [octal] `755` instead of [octal] `100755`), which would result in unpacking it with incorrect permissions.

Fix files not getting proper permissions in tgz2zip

---

maven/templates/deploy.py

Recent addition of signing Maven artifacts (#133) broke existing deployments since they don't satisfy `gpg key should already be present in keyring` requirement. This PR allows to explicitly specify whether you need to generate and deploy signatures for artifacts.
If `--gpg` is not passed as command-line argument, no action to generate and deploy signature is taken

Optionally sign Maven artifacts

---

github/deploy.py

Fix #108
This pull requests brings in support for deploying files not available as `bazel` targets.
- Support optionally supplying `--archive ARCHIVE` command-line argument
- Command-line argument parsing is now done by `argparse`
- Couple of spaces to make code more PEP8-compliant
Sample invocation:
```
bazel run //:deploy-github -- $CIRCLE_SHA1 --archive $(pwd)/archive-with-deployables.zip
```

Allow usage of deploy-github with externally supplied archives

---

README.md
apt/rules.bzl
aws/rules.bzl
brew/rules.bzl
common/assemble_versioned.bzl
common/checksum.bzl
common/generate_json_config.bzl
common/java_deps.bzl
common/rules.bzl
common/tgz2zip.bzl
gcp/rules.bzl
github/rules.bzl
maven/templates/rules.bzl
npm/rules.bzl
packer/rules.bzl
pip/rules.bzl
rpm/rules.bzl

Previously, rules were not documented so user would have to read the implementation to understand the purpose of this rule. This PR introduces description for every rule/macro.
Document all rules/macros

Update docs for all rules

---

pip/assemble.py
pip/rules.bzl

Previously, `assemble_pip` required you to supply `package_root` to indicate at which directory your source files hierarchy starts. This PR removes this argument and instead relies on data from `ctx.attr.target[PyInfo].imports` (attached by `bazel`)
- Remove `package_root` from `assemble_pip` arguments
- Replace `--package_root` [single arg] with `--imports` [multiple args] in Python package assembler implementation
- Instead of ignoring *all* external sources, only ignore those that belong to PyPI packages

Improve assemble_pip to autodetect files to include into Python tarball

---

github/rules.bzl

Incremental work on #150 for `deploy_github` rule
- Make `version_file` in `deploy_github` optional
- Add missing symlink to `VERSION`
`bazel run --define version=$(git rev-parse HEAD) //:deploy-github`

Streamlined versioning for deploy_github

---

.github/CODEOWNERS

We've added Ganesh and Max as code owners.

Add Ganesh and Max as code owners

---

common/assemble_versioned.bzl

Partial work on #150
`assemble_versioned` no longer requires user to provide `version_file`. Instead it can be specified as `bazel build --define version=$(cat VERSION) <assemble_versioned_target>`

Refactor how version is provided to assemble_versioned

---

rpm/rules.bzl

Adding option to pass `tags` to the `assemble_rpm` rule.
This can be beneficial in the cases when tags are intensively used. This would also allow to specify `tags = ["manual"]` so that `.rpm` is ignored when running `bazel build //...` and similar for the setups where `rpmbuild` is not available.
ref: #205
- Adds a new `tags` argument to the `assemble_rpm` macro and pass it to all wrapped rules.
Additionally:
- remove references to the `.deb` packages
- add `workspace_refs` argument doc
RESOLVES #205

Pass tags attribute to all rpm internal rules.

---

maven/templates/pom.xml
maven/templates/rules.bzl

Add support for MIT license in pom.xml template
added MIT as an option for `assemble_maven`  license field

Add support for MIT license

---

.circleci/config.yml
WORKSPACE

We have restructured WORKSPACE for readability

Restructure WORKSPACE for readability

---

maven/templates/deploy.py

Fixed maven deploy to be uploadable to github package.
Also allowed when uploading http status code 200. (clean up from #240)

maven(github packages) - return http status code 200

---

npm/rules.bzl

Update npm rules, fixing a incorrect retrieval of `target` in a previous PR

Update npm rules v2

---

brew/templates/deploy.py

Currently, `deploy_brew` does no verification on the archive that it downloads from GitHub as well as accepts "404 Not found" as an acceptable artifact which leads to harder-to-debug errors.
* Add `--fail` argument to `curl`: this would fail immediately when trying to download a non-reachable (e.g. private) release
* Verify that zip file is correct by trying to open it (would fail if file exists but is not a valid ZIP) and running `testzip` (would fail if file exists and is a valid but corrupt ZIP)

Make deploy_brew fail faster

---

WORKSPACE
bazelbuild_rules_python-export-requirements-bzl-for-stardoc.patch
common/deps.bzl
pip/deps.bzl

Upgrade `rules-python` to `0.1.0` in order to speed up Client Python CI
Upgrade `@rules_python` to latest release and adapt syntax accordingly

Upgrade @rules_python

---

WORKSPACE
common/deps.bzl
maven/BUILD
maven/JarAssembler.kt
maven/PomGenerator.kt
maven/deps.bzl
maven/new_rules.bzl

Rewrite `assemble_maven` in Kotlin in order for us to understand it better and improve its maintability/readability.
Implement `assemble_maven` in `@graknlabs_bazel_distribution//maven:new_rules.bzl`

Updated version of assemble_maven rewritten in Kotlin

---

WORKSPACE
maven/new_rules.bzl

Improve new `assemble_maven` implementation by addressing the rest of review comments.
Address review comments from graknlabs/bazel-distribution#293

Address review comments in assemble_maven

---

packer/rules.bzl
packer/templates/deploy_packer.py

Allow overwriting existing image when deploying packer image.
Adding overwrite attribute for packer deploy rule.

Allow overwriting existing image when deploying packer image

---

BUILD
LICENSE
NOTICE
WORKSPACE
apt/rules.bzl
aws/rules.bzl
azure/rules.bzl
common/deps.bzl
common/rules.bzl
gcp/rules.bzl
maven/rules.bzl
packer/rules.bzl
pip/BUILD
pip/deps.bzl
pip/rules.bzl
rpm/rules.bzl

Advance organisation-wide name change
Rename everything Grakn Labs to Vaticle

Renamed 'Grakn Labs' to 'Vaticle'

---

packer/deps.bzl

Address VM image generation problems we've been facing by upgrading the tool used to generate such images.
Upgrade Packer to latest released version

Upgrade Packer to latest release

---

npm/deploy/Deployer.kt

We observed odd behaviour where the auth token used by `deploy_npm` to publish npm packages was not being picked up when written to a `.npmrc` file. So, we now pass it as a command-line parameter.
Pass deploy_npm's auth token as command line param
unblocks release of `typedb-client-nodejs`

Pass deploy_npm's auth token as command line param

---

crates/rules.bzl

`assemble_crate` now supports procedural macro dependencies, and is more reliable at correctly detecting the crate names of all dependencies. In particular, crates with hyphens (such as `async-trait`) should no longer cause issues.
Previously `assemble_crate` aggregated dependency info via only the `deps` attribute of a `rust_*` target. Now, `proc_macro_deps` is traversed as well.
Also, crate name detection has been reworked. Because `rules_rust` doesn't expose the original name of the crate downloaded from Cargo anywhere, we were unable to reliably get that crate name and put it into `Cargo.toml`. Now, we use string parsing against the target's label. This works because the label is (e.g):
```
@crates__async-trait-0.36.0//:async_trait
```
We take everything up to + excluding the first …

Support proc macros and fix dependency name detection in `assemble_crate`

---

common/uploader/nexus.py
maven/templates/deploy.py

Fixes a bug causing maven deployments to fail
* Passes the ElementTree Element text instead of the element to the uploader.

Fix bug with maven deployment 

---

common/deps.bzl
pip/BUILD

Bump rules python to 0.31.0
